package models;
// Generated 30 dic. 2020 15:22:15 by Hibernate Tools 5.4.18.Final

import java.util.Date;

/**
 * Anuncio generated by hbm2java
 */
public class Anuncio implements java.io.Serializable {

	private int codigo;
	private AgenciaVentaCoche agenciaVentaCoche;
	private Vehiculo vehiculo;
	private Date fechaPublicacion;
	private float precio;
	private float numKm;

	public Anuncio() {
	}

	public Anuncio(int codigo, AgenciaVentaCoche agenciaVentaCoche, Vehiculo vehiculo, Date fechaPublicacion,
			float precio, float numKm) {
		this.codigo = codigo;
		this.agenciaVentaCoche = agenciaVentaCoche;
		this.vehiculo = vehiculo;
		this.fechaPublicacion = fechaPublicacion;
		this.precio = precio;
		this.numKm = numKm;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public AgenciaVentaCoche getAgenciaVentaCoche() {
		return this.agenciaVentaCoche;
	}

	public void setAgenciaVentaCoche(AgenciaVentaCoche agenciaVentaCoche) {
		this.agenciaVentaCoche = agenciaVentaCoche;
	}

	public Vehiculo getVehiculo() {
		return this.vehiculo;
	}

	public void setVehiculo(Vehiculo vehiculo) {
		this.vehiculo = vehiculo;
	}

	public Date getFechaPublicacion() {
		return this.fechaPublicacion;
	}

	public void setFechaPublicacion(Date fechaPublicacion) {
		this.fechaPublicacion = fechaPublicacion;
	}

	public float getPrecio() {
		return this.precio;
	}

	public void setPrecio(float precio) {
		this.precio = precio;
	}

	public float getNumKm() {
		return this.numKm;
	}

	public void setNumKm(float numKm) {
		this.numKm = numKm;
	}

}
