package models;
// Generated 30 dic. 2020 15:22:15 by Hibernate Tools 5.4.18.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais implements java.io.Serializable {

	private String nombre;
	private Set ciudadeses = new HashSet(0);

	public Pais() {
	}

	public Pais(String nombre) {
		this.nombre = nombre;
	}

	public Pais(String nombre, Set ciudadeses) {
		this.nombre = nombre;
		this.ciudadeses = ciudadeses;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getCiudadeses() {
		return this.ciudadeses;
	}

	public void setCiudadeses(Set ciudadeses) {
		this.ciudadeses = ciudadeses;
	}

}
