package models;
// Generated 30 dic. 2020 15:22:15 by Hibernate Tools 5.4.18.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo implements java.io.Serializable {

	private long numeroOferta;
	private AgenciaVentaCoche agenciaVentaCoche;
	private String marca;
	private String modelo;
	private long numeroPlazas;
	private String tipoCambio;
	private Date anyo;
	private String combustible;
	private String tipo;
	private Set anuncios = new HashSet(0);

	public Vehiculo() {
	}

	public Vehiculo(long numeroOferta, AgenciaVentaCoche agenciaVentaCoche, String marca, String modelo,
			long numeroPlazas, String tipoCambio, Date anyo, String combustible, String tipo) {
		this.numeroOferta = numeroOferta;
		this.agenciaVentaCoche = agenciaVentaCoche;
		this.marca = marca;
		this.modelo = modelo;
		this.numeroPlazas = numeroPlazas;
		this.tipoCambio = tipoCambio;
		this.anyo = anyo;
		this.combustible = combustible;
		this.tipo = tipo;
	}

	public Vehiculo(long numeroOferta, AgenciaVentaCoche agenciaVentaCoche, String marca, String modelo,
			long numeroPlazas, String tipoCambio, Date anyo, String combustible, String tipo, Set anuncios) {
		this.numeroOferta = numeroOferta;
		this.agenciaVentaCoche = agenciaVentaCoche;
		this.marca = marca;
		this.modelo = modelo;
		this.numeroPlazas = numeroPlazas;
		this.tipoCambio = tipoCambio;
		this.anyo = anyo;
		this.combustible = combustible;
		this.tipo = tipo;
		this.anuncios = anuncios;
	}

	public long getNumeroOferta() {
		return this.numeroOferta;
	}

	public void setNumeroOferta(long numeroOferta) {
		this.numeroOferta = numeroOferta;
	}

	public AgenciaVentaCoche getAgenciaVentaCoche() {
		return this.agenciaVentaCoche;
	}

	public void setAgenciaVentaCoche(AgenciaVentaCoche agenciaVentaCoche) {
		this.agenciaVentaCoche = agenciaVentaCoche;
	}

	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	public long getNumeroPlazas() {
		return this.numeroPlazas;
	}

	public void setNumeroPlazas(long numeroPlazas) {
		this.numeroPlazas = numeroPlazas;
	}

	public String getTipoCambio() {
		return this.tipoCambio;
	}

	public void setTipoCambio(String tipoCambio) {
		this.tipoCambio = tipoCambio;
	}

	public Date getAnyo() {
		return this.anyo;
	}

	public void setAnyo(Date anyo) {
		this.anyo = anyo;
	}

	public String getCombustible() {
		return this.combustible;
	}

	public void setCombustible(String combustible) {
		this.combustible = combustible;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Set getAnuncios() {
		return this.anuncios;
	}

	public void setAnuncios(Set anuncios) {
		this.anuncios = anuncios;
	}

}
